[package]
name = "rover-std"
version = "0.1.0"
authors = ["Apollo Developers <opensource@apollographql.com>"]
edition = "2021"

publish = false

[dependencies]
atty = { workspace = true }
anyhow = { workspace = true }
camino = { workspace = true }
console = { workspace = true }
futures = { workspace = true }
notify = { workspace = true, default-features = false, features = [ "macos_kqueue"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
test-log = { workspace = true }
uuid = { workspace = true, features = ["v4"] }